# Generated by Django 5.2 on 2025-04-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='weight',
            field=models.IntegerField(default=0, max_length=50),
        ),
    ]
