# Generated by Django 5.2 on 2025-04-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_person_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
