# Generated by Django 5.2 on 2025-04-29 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_person_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='height',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='weight',
            field=models.IntegerField(default=100),
        ),
    ]
