# Generated by Django 5.2 on 2025-04-29 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_person_height_alter_person_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(default='male', max_length=10),
        ),
        migrations.AlterModelTable(
            name='person',
            table='person',
        ),
    ]
