# Generated by Django 5.2 on 2025-04-29 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_person_gender_alter_person_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(default='male', max_length=50),
        ),
    ]
